name: waltz_robot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pinocchio
  - numpy
  - pytorch
  - torchvision
  - pip
  - matplotlib
  - robot_descriptions
  - robomeshcat
  - meshcat
  - pycollada
  - joblib
  - pandas
  - pink
  - ffmpeg
  - time
  - pydub
  - opencv-python