name: waltz_robot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pinocchio
  - numpy
  - pytorch
  - torchvision
  - matplotlib
  - robot_descriptions
  - pycollada
  - joblib
  - pandas
  - pink
  - ffmpeg
  - time
  - pydub
  - opencv
  - meshcat-python
  - pip