name: waltz_robot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pinocchio
  - meshcat-python
  - example-robot-data
  - jupyterlab
  - ipywidgets
  - matplotlib
  - scipy
  - quadprog
  - keras
  - tensorflow
  - gym
  - tqdm
  - gymnasium
  - imageio
  - mujoco=2.3.7
  - rich
  - stable-baselines3
  - tensorboard
  - pink
  - robot_descriptions
  - joblib
  - pip

# Meshcat_shapes must be installed with pip.